# Note: mario.lan refers to my personal pc's domain in my intranet, of course change as you need.

services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: 'OLLAMA_BASE_URL=http://mario.lan:11434'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - ${PATH_OPEN_WEBUI_DATA}:/app/backend/data
    ports:
      - 4000:8080
    environment:
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - OAUTH_PROVIDER_NAME
      - OPENID_PROVIDER_URL
      - OPENID_REDIRECT_URI
      - WEBUI_URL
      - ENABLE_OAUTH_SIGNUP
      - ENABLE_LOGIN_FORM
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL
      - OLLAMA_BASE_URL
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
