services:
  dashy:
    container_name: Dashy

    image: lissy93/dashy:latest

    # Pass in your config file below, by specifying the path on your host machine
    # volumes:
      # - /path/to/my-config.yml:/app/user-data/conf.yml
      # - /path/to/item-icons:/app/user-data/item-icons/
    volumes:
      - ${PATH_DASHY_DATA}:/app/user-data:rw


    # Set port that web service will be served on. Keep container port as 8080
    ports:
      - 11080:8080

    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1000
      - GID=1000

    # Specify restart policy
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s