services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
      - ${PATH_ADGUARD_HOME_CONF}:/opt/adguardhome/conf
      - ${PATH_ADGUARD_HOME_WORK}:/opt/adguardhome/work
    network_mode: host
    # ports:
    #     # DNS
    #     - 53:53
    #     # DHCP server
    #     - 67:67/udp
    #     - 68:68/udp
    #     # HTTPS/DNS-over-HTTPS
    #     - 443:443/tcp
    #     # DNS-over-TLS
    #     - 853:853/tcp
    #     # DNS-over-QUIC
    #     - 853:853/udp
    #     # DNSCrypt
    #     - 5443:5443/tcp
    #     - 5443:5443/udp
    #     # WebUI
    #     - 3000:3000/tcp
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguardhome.entrypoints=insecure"
      - "traefik.http.routers.adguardhome.rule=Host(`adguard.$DOMAIN`)"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
      # - "traefik.http.routers.adguardhome.tls.certresolver=le"
    